# Task Manager Application Deployment and Service
# Deployment - Manages the Task Manager application Pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-deployment
  namespace: "02220177"
  labels:
    app: taskmanager
    component: frontend
    version: v1
    student: "02220177"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
        version: v1
    spec:
      containers:
        - name: taskmanager
          image: yena5/task-manager:e4df4ae0e9e3e17259eb7217a1505dbb1bc63da6
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DATABASE_URL
              value: "postgresql://myuser:uWhSZwv54wXv1T7F@10.104.0.6:5432/02220177"
            - name: SECRET_KEY
              value: "kubernetes-secret-key-02220177"
            - name: FLASK_ENV
              value: "production"
---
# Service - Provides stable network access to the Task Manager Pods
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
  namespace: "02220177"
  labels:
    app: taskmanager
    student: "02220177"
spec:
  selector:
    app: taskmanager
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
  template:
    spec:
      containers:
        - image: yena5/task-manager:e4df4ae0e9e3e17259eb7217a1505dbb1bc63da6
